# Site settings
title: Karen Cranston, PhD
email: karen.cranston@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Karen Cranston, PhD. Computational evolutionary biologist at Duke. Building the Open
  Tree of Life. Teaching computational skills.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kcranston.github.io" # the base hostname & protocol for your site
twitter_username: kcranstn
github_username:  kcranston
orcid: 0000-0002-4798-9499
disqus_shortname: https-kcranston-github-io

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Research Scientist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
